#!/bin/sh

# still in development
# TBA : more colors, faster implementation, more banners

#COLORS
pink=$(tput setaf 175)
lpink=$(tput setaf 224)
green=$(tput setaf 71)
white=$(tput setaf 255)
lblue=$(tput setaf 153)
red=$(tput setaf 160)
yellow=$(tput setaf 226)

reset=$(tput sgr0)
bold=$(tput bold)

#BASIC INFO
OS=$(grep PRETTY_NAME /etc/os-release | head -n 1 | awk -F"=" {'print $2'} | sed -e 's/^"//' -e 's/"$//')
KERNEL="$(uname -r)"
USR="$(whoami)@$(cat /etc/hostname)"
SHELL=$(grep "$USER" /etc/passwd | awk -F"/" '{printf "%s\n", $5}')
UPTIME_MIN=$(awk '{printf "%d\n", $1 / 60 % 60}' /proc/uptime)
UPTIME_HRS=$(awk '{printf "%d\n", $1 / 60 / 60 % 24}' /proc/uptime)
UPTIME_DAY=$(awk '{printf "%d\n", $1 / 60 / 60 / 24}' /proc/uptime)

#MEMORY (MEM_USE IS NOT 100% ACCURATE)
MEM_FRE=$(grep MemFree /proc/meminfo | awk '{printf "%d\n", $2 / 1024}')
MEM_BUF=$(grep Buffers /proc/meminfo | awk '{printf "%d\n", $2 / 1024}')
MEM_REC=$(grep SReclaimable /proc/meminfo | awk '{printf "%d\n", $2 / 1024}')
MEM_CCH=$(grep Cached /proc/meminfo | head -n 1 | awk '{printf "%d\n", $2 / 1024}')
MEM_TOT=$(grep MemTotal /proc/meminfo | awk '{printf "%d\n", $2 / 1024}')
MEM_USE=$(expr $MEM_TOT - $MEM_FRE - $MEM_REC - $MEM_BUF - $MEM_CCH)

OS_NAME=$(grep NAME /etc/os-release | head -n 1 | awk -F"=" {'print $2'} | sed -e 's/^"//' -e 's/"$//')
case $OS_NAME in
    [Aa]rch*)
        BANNER0="       /\         "
        BANNER1="      /  \        "
        BANNER2="     /\   \       "
        BANNER3="    /      \      "
        BANNER4="   /   ,,   \     "
        BANNER5="  /   |  |  -\    "
        BANNER6=" /_-''    ''-_\   "
        PKGS="$(pacman -Q | wc -l)"
        ;;
    [Ff]edora*)
        BANNER0="        ,.......    "
        BANNER1="       |   ,..  |   "
        BANNER2="   ,...|  |..,'_'   "
        BANNER3=" .' ,..   ...'      "
        BANNER4=" | |   |  |         "
        BANNER5=" | '...'  |         "
        BANNER6="  '------'          "
        PKGS="$(rpm -qa | wc -l)"
        ;;
    [Uu]buntu*)
        BANNER0="                 "
        BANNER1="     , ---(__)   "
        BANNER2="    /  ___  \    "
        BANNER3=" (__) |   |      "
        BANNER4="    \  --- _/    "
        BANNER5="     ' ---(__)   "
        BANNER6="                 "
        PKGS="$(dpkg-query -f '${binary:Package}\n' -W | wc -l)"
        ;;
    [Dd]ebian*)
        BANNER0="   ______    "
        BANNER1=" //  ,.  \   "
        BANNER2=" |  / -' /   "
        BANNER3=" |  \_.-'    "
        BANNER4=" '.          "
        BANNER5="   '-__      "
        BANNER6="             "
        PKGS="$(dpkg-query -f '${binary:Package}\n' -W | wc -l)"
        ;;
esac

#CONFIGURATION
#colors are available at the top of the file

col=$lpink

printf "${bold}${col}${BANNER0}USR${reset}: ${bold}${USR}${reset}\n"
printf "${bold}${col}${BANNER1}OS${reset}: ${bold}${OS}${reset}\n"
printf "${bold}${col}${BANNER2}KERNEL${reset}: ${bold}${KERNEL}${reset}\n"
printf "${bold}${col}${BANNER3}PKGS${reset}: ${bold}${PKGS}${reset}\n"
printf "${bold}${col}${BANNER4}SHELL${reset}: ${bold}${SHELL}${reset}\n" 
printf "${bold}${col}${BANNER5}UPTIME${reset}: ${bold}${UPTIME_DAY}d ${UPTIME_HRS}h ${UPTIME_MIN}m${reset}\n"
printf "${bold}${col}${BANNER6}MEM${reset}: ${bold}${MEM_USE}M/${MEM_TOT}M${reset}\n\n"

